name: CI

on:
  # Compare the preceeding commit of main -> to the current commit of the main branch.
  # (Note: To compare changes between the last pushed commit to the remote main branch set `since_last_remote_commit: true`)
  push:
    branches:
      - master
  # # Compare the last commit of main -> to the current commit of a PR branch.
  # # (Note: To compare changes between the last pushed commit to the remote PR branch set `since_last_remote_commit: true`)
  # pull_request:
  #   branches:
  #     - master


jobs:
  search_changes:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 2
      - name: Get changed files in the services folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v35
        with:
          files: |
            services/**
          dir_names: "true"
          separator: ","


      - name: Run step if any directories in the services folder change
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          echo "One or more files in the docs folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"


  deploy_changed:
    strategy:
      matrix:
        dir: [${{ steps.changed-files-specific.outputs.all_changed_files }}]
    steps:
      name: deploy ${{matrix.dir}}
      run: echo ${{dir}}
