on:
  workflow_call:
    inputs:
      changed-dirs:
        required: true
        type: string

jobs:
  matrix:
      runs-on: ubuntu-latest
      outputs:
        matrix: ${{ steps.set-matrix.outputs.matrix }}
      steps:
        - uses: actions/checkout@v3
        - name: set matrix
          id: set-matrix
          run: |
            dirs=${{inputs.changed-dirs}}
            dirs="[ { ${dirs//,/", "} } ]"
            echo "$dirs"
            echo "::set-output name=matrix::$matrix"

  check-matrix:
    runs-on: ubuntu-latest
    needs: [search_changes, matrix]
    steps:
      - name: Install json2yaml
        run: |
          sudo npm install -g json2yaml

      - name: Check matrix definition
        run: |
          matrix='${{ needs.matrix.outputs.matrix }}'
          echo $matrix
          echo $matrix | jq .
          echo $matrix | json2yaml

  deploy:
    needs: [search_changes, matrix]

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix.outputs.matrix)}}

    steps:
      - name: deploy ${{matrix.dir}}
        run: echo "deploy ${{dir}}"
